config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:index, :show]

  get '/contact', to: 'contacts#new', as: 'new_message'
  post 'contacs', to: 'contacs#create', as: 'create_message'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

validates :name, :content, presence: true
validates :email,
          presence: true,
          format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ },
          on: :create
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<h1>Message me</h1>

<%= simple_form_for @contact, url: new_message_url do |f| %>
<%= f.input :name %>
<%= f.input :email %>
<%= f.input :message %>
<%= f.submit 'Send message' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% if current_page?(projects_path) %>
      <div class="background" style="background: url(<%= image_path "office2.jpg" %>);">
      <% end %>
  <%= render 'shared/navbar' %>
  <div class="contour">
    <%= yield %>
    </div>
    </div>


    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="welcome">
    <p>Hello, welcome to my portfolio</p>
  </div>
</div>

<h2 class="intertitre">About me</h2>

<div class="about">
  <div class="bio">
    <h2>Bio</h2>
    <p class="me">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi atque ratione nesciunt, excepturi dicta veritatis quos suscipit perspiciatis totam eius harum ipsam cupiditate iure blanditiis corrupti, adipisci odio hic unde</p>
  </div>

</div>

<h2 class="intertitre">Work experience</h2>

<div class="experiences">


  </div>
</div>

<h2 class="intertitre">Education</h2>

<div class="education">

  <div class="a">
    <div class="wagon">
    </div>

    <div class="aix">
    </div>
  </div>

  <div class="b">
    <div class="lyon">
    </div>

    <div class="china">
    </div>
  </div>

</div>




<!-- <div class="projects" id="projects">

 <div class="projetca">
    <h2>Project</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi atque ratione nesciunt, excepturi dicta veritatis quos suscipit perspiciatis totam eius harum ipsam cupiditate iure blanditiis corrupti, adipisci odio hic unde!</p>
  </div>
</div> -->

app/views/projects/index.html.erb
<div class="back">

  <div class="decoration">
  </div>

  <div class="content-project">

    <div class="project-card">

    <div class="project-description">
      <h2 class="text-center">Titre du projet</h2>
      <p>Desktop / mobile app</p>
      <p>Descritpion</p>
      <p>Technology</p>
      <p>Online / offline</p>

    </div>
    <div class="proto">

    </div>

    </div>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "projects", projects_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "contact", root_path(anchor: 'contact'), class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>